### ISSUE TITLE
Remux does not apply filters

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#101]
I just tried to create a clip of the Darla scene from Finding Nemo with BEQ applied and keeping the original audio, but the resulting file had two identical tracks.

Steps:
1. I loaded the Finding Nemo BEQ with the filters I wanted to apply.  It was the only signal loaded.
2. I opened the remux dialog and set it up as follows:
![image](https://user-images.githubusercontent.com/42757020/46907394-aec56100-cedf-11e8-9ee8-ada5b76b08a1.png)

The resulting file does snip the video properly, has two FLAC tracks as expected, but they sound identical, and extracting them and graphing them they look identical there as well.

Here's the filter file with .txt extension added so I can attach it:
[tmpvlbkn3m0.filt.txt](https://github.com/3ll3d00d/beqdesigner/files/2475611/tmpvlbkn3m0.filt.txt)

**Comment by 3ll3d00d** [comment]
strange, certainly works in other situations and the command looks ok so I wonder what is failing here

**Comment by 3ll3d00d** [comment]
I haven't been able to pin down exactly when it doesn't work yet, I thought the trigger was the "include original audio"  option at first but I can show this working so it's not that (or not just that anyway). I'm now thinking it's an issue with >2 channel files but need to spend more time testing this. Any time you can put into finding cases that work vs cases that don't would be useful, even just posting here with "this config works" or "this one doesn't" might provide some pointers.

**Comment by 3ll3d00d** [comment]
I have fixed a couple of bugs here, specifically

* stacked shelf filters were not applied (only the 1st one was)
* slave signals (the linked feature) were ignored by the filtering

the first issue is a factor in your particular case reported above so you could give it a try with separate filters instead to see if the issue was more that the filter was much weaker than expected rather than not filtered at all

**Comment by aron7awol** [comment]
That was the first one I tried so I don't have any cases that work yet, but I'll test some others and see what happens.

I don't think the stacked filter bug was the main culprit, because I extracted both tracks and they were identical.

**Comment by 3ll3d00d** [comment]
the last commit fixes a bug where it was extracting the wrong track when mixing to mono, this means the following would be identical even if the underlying track was correct

* apply some filters via remux and include original audio & the video track
* extract the original audio from the resulting remuxed track 
* extract the filtered audio from the resulting remuxed track

these last two would show as identical because the last extract was actually pulling out the 1st track instead

this means the build you have will only process the 1st audio stream

I'll push out a new build tomorrow with this fix

**Comment by aron7awol** [comment]
Ahh, that probably fully explains it.  The cascaded filter bug explains the listening test results, and the selected audio track bug explains the graphs looking identical.  Good catch!
