### ISSUE TITLE
Use R128 analysis to normalise tracks to a consistent level

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#120]
Use ebur128 output from ffmpeg to determine the overall level of the track, use this to offset the current track level so that different tracks will automatically use the same colour scheme. 

It must be possible to use a different channel for R128 analysis, e.g. use the C channel for R128 when analysing the LFE

_Originally posted by @3ll3d00d in https://github.com/3ll3d00d/beqdesigner/issues/116#issuecomment-430752083_

**Comment by aron7awol** [comment]
I wonder if measuring this for the mixed to mono track would give the best approximation of overall level, since it would account for times where multiple channels are loud at the same time.  Just something worth experimenting with.  I'd like to see that R128 value for some of the known loud/normal/soft movies that were mentioned in the BEQ thread.

**Comment by 3ll3d00d** [comment]
the R128 analysis in ffmpeg is v v slow so this doesn't seem particularly feasible to implement (without using some lengthy offline batch analysis and storing the data separately)

**Comment by aron7awol** [comment]
I played around with this a little bit after seeing your post in the smoothing issue thread...

When you tested this, what was your ffmpeg command?  Did you try it on the full file with all 6/8 channels, or did you try it on a mixed-to-mono track?

I happen to have some mixed-to-mono tracks for Ready Player One since I've been using them a lot for testing, and I have it in mono at 1kHz, 8kHz, and original sampling rate.  I figured R128 analysis would need the original sampling rate, but thought I'd test that anyway.

My results:
![image](https://user-images.githubusercontent.com/42757020/48590221-b461fc80-e90c-11e8-888a-c1ae2f143c3a.png)

I'm somewhat surprised the result for 8kHz and 48kHz came out so close.  I haven't tested any other mixes, so I really have no idea what the typical range of these values are, but maybe the difference between 48kHz and 1kHz isn't even that large?

On these mono tracks, the analysis ran at almost exactly the same speed on all 3 files, despite their large differences in sample rate and thus filesize.  The appeared to be totally CPU-limited on my machine, which has a modest i5-5250U, and still ran at a quite speedy ~53x, and thus was able to process the entire file in ~2.5 minutes.  Does that match your experience?

**Comment by aron7awol** [comment]
I can actually run two at once and both still run at 47x on the same machine.

**Comment by 3ll3d00d** [comment]
I don't recall the exact command, it was something like http://k.ylo.ph/2016/04/04/loudnorm.html but with the default parameter values (as per http://ffmpeg.org/ffmpeg-filters.html#loudnorm) 

It did take minutes to run, more than a couple for sure. I was on a relatively lightweight laptop though. I would have thought it is I/O bound rather than CPU bound mind you as it has to read the track to decode it and then analyse it which means streaming it over the network. Hence the comment above re a batch mode which then means somewhere to store the results, a way to format them and somewhere to subsequently load them up.

**Comment by aron7awol** [comment]
I'm running this command:
ffmpeg -i "input.wav" -af loudnorm=I=-16:TP=-1.5:LRA=11:print_format=summary -f null -

I do think it would become I/O bound if working with a larger file, but having them mixed-to-mono already cuts the file size down to a reasonable size (1GB) even at the original sampling rate, so it is reading <10MB/sec at the 50x speed.  At that point, it is CPU-bound, and that's why I was getting the same speeds at 1kHz, 8kHz, and original sampling rates.  I'm running these on my Intel NUC, which has a laptop chip in it, so it is not a powerhouse.

I would certainly expect it to move to being I/O bound if it is run on a full 20GB MKV file that contains the video track and audio tracks, similar to how extraction is I/O bound now.  However, I am thinking there is probably a good compromise on sampling rate (maybe 2kHz or 4kHz) that gives accurate R128 results, and I can use the same file for BEQ design.  That way there is no wasted step, the track is extracted and mixed-to-mono once and it can be used for both.  I think the early results with R128 on the 1kHz tracks are very promising, and I will do further testing with 2kHz and 4kHz to see at what point it becomes almost as accurate as 48kHz.

**Comment by aron7awol** [comment]
I found an error in my previous data on Ready Player One, so I re-tested that movie and Dunkirk at 1kHz, 2kHz, 4kHz, 8kHz, and the original 48kHz.

It's very consistent overall, and also very consistent in the change with sample rate.  The error when using a sample rate even as low as 1kHz only appears to be ~0.5dB

![image](https://user-images.githubusercontent.com/42757020/48637711-8926ee00-e99c-11e8-8642-8c60076ffb3e.png)

**Comment by aron7awol** [comment]
I tested some on my quad-core i7-4790K machine and it can do 4 simultaneously at 80x speed!  So it can basically do 4 2-hour movies in 1.5 minutes.

**Comment by 3ll3d00d** [comment]
I take it you are using measured_i for comparing tracks?

I assume this doesn't vary with the loudness parameters right? I would have thought it doesn't mattet but just checking because you are not using the ebu r128 target with those parameters

**Comment by aron7awol** [comment]
I compiled all 4 measured values for about 90 different movies (1kHz sample rate) because I wanted to see if looking beyond measured_i would be beneficial.  measured_threshold is particularly interesting to me because I haven't been able to find documentation on it, it's highly correlated with measured_i but differs quite a bit on some particular mixes.  I am using TP as a double-check, and only looking at LRA as a measure of dynamic range as an observation.

If you know what exactly threshold is measuring, or find any documentation on it, please share.

I agree that I don't think the loudness parameters I use make any difference since I am only doing a first pass, but I haven't tested that.

**Comment by 3ll3d00d** [comment]
The spec describes what the relative threshold is and how it relates to both the reported loudness and the LRA

https://tech.ebu.ch/docs/tech/tech3342.pdf

**Comment by 3ll3d00d** [comment]
It might interesting to get loudness by time (as per the example in the spec) into the app if I can find something that can output that level of detail.

**Comment by 3ll3d00d** [comment]
I could also add this to the batch extract?

**Comment by aron7awol** [comment]
Thanks for the link.

I agree loudness by time could be very interesting.

The batch extract interface would seem to be the perfect match for this!  Do you have any ideas as far as output format?

**Comment by aron7awol** [comment]
The documentation states:
"The relative threshold is set to a level of −20 LU relative to the absolute-gated loudness level."
 
In the 100 films I've measured so far, the difference between measured_i and measured_threshold varies between 11.4 and 15.3 LU.  This difference is highly correlated with measured_LRA, but not perfectly.  For example, "Mother!" has the highest difference at 15.3, but its LRA is a middle-of-the-pack 23.9.

**Comment by aron7awol** [comment]
I do think if you could figure out a way to show loudness by time that would be huge, because in my testing I find certain scenes that force me to turn the volume down and if I those could be quantified that would shed a ton of light on how the limits of harshness measure.
