### ISSUE TITLE
"+" button when editing filter is grayed out until changing gain

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#133]
Often times the modification to the filter is by changing one of the other fields such as Freq, Q, or Count, but none of those cause the "+" button to become active.

I often edit filters and hit the "+" to see the result, then make another edit and hit it again, repeating until I am satisfied with that filter.

This brings up a side issue that I've never mentioned until now.  When adding a new filter, hitting "+" adds it (as expected) but then if it is edited and "+" is clicked again, it creates another new filter.  This is probably expected behavior, and my using the "+" button as a "save but don't exit the dialog" button is maybe not expected behavior, but it's extremely convenient when experimenting with filters.

What I end up doing is creating a new filter and saving and exiting, then editing it so I can use the "+" button as my "save but don't exit" button.  Maybe the solution to all of this is actually have a button for that?

**Comment by 3ll3d00d** [comment]
+ means add a new filter and the floppy icon is save the current one and exit. I couldn't think of an icon to distinguish between save and save/exit hence why there is currently no such button :) happy to add one though

If + is enabled when you change gain then that is probably a bug tbh, need to double check code to be sure but it sounds like a bug to me

**Comment by aron7awol** [comment]
Up until one of these recent new versions that + button was always enabled and I used it often.  It starting out disabled is new behavior :)

**Comment by 3ll3d00d** [comment]
The reason it is (meant to be) disabled is because it means the preview is incorrect as it shows the effect of editing the selected filter not adding a new one.

It sounds like we want the filter dialog to behave more similarly whether editing or adding and without having  to close the reopen the dialog. This means 

- can add new at any time
- can change which filter is being edited or choose to be adding a new one
- screen stays open until you hit close

I guess it might also be nice to be able to

- make changes to multiple filters and then save the entire set of changes in one go 
- add a filter target curve
- show all filters on the graph

**Comment by aron7awol** [comment]
I agree with you 100%

**Comment by 3ll3d00d** [comment]
the commit above fixes the originally intended behaviour, the other improvements will come later
