### ISSUE TITLE
Peak spectrum does not apply MV offset

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#172]
I generated two peak spectrum graphs, one by using the new offset functionality, and one by using the previous gain functionality.

The offset functionality does not appear to be applying to the peak spectrum.
![christmaschronicle](https://user-images.githubusercontent.com/42757020/50489305-ef0f8800-09d4-11e9-8ac1-21767c0024bb.png)
![christmaschronicles](https://user-images.githubusercontent.com/42757020/50489306-ef0f8800-09d4-11e9-8514-5f2931ebfc6b.png)

**Comment by 3ll3d00d** [comment]
How did you produce the graph? Via the waveform view at the bottom of the main screen or...?

**Comment by aron7awol** [comment]
The waveform in Analyse Audio is the same.  If I add a signal with a negative offset, the waveform does not reflect that offset so it says I have less headroom than I really do.

**Comment by 3ll3d00d** [comment]
this is as expected because "Analyse Audio" operates on the selected file which is loaded again and then you select a filter to apply. The offset is applied when the signal is read though and is not part of the filter so there is no offset to apply here.

The way to do this is to use the waveform view to get to the spectrum comparison

![image](https://user-images.githubusercontent.com/2487509/50493205-f0ac7080-0a13-11e9-9f54-6a41351a9fc4.png)

then compare the 2 signals, the checkbox applies the filter for that signal so you'll want to have one checkbox checked

![image](https://user-images.githubusercontent.com/2487509/50493241-218ca580-0a14-11e9-96ff-5fcf996220d6.png)

if you wanted to compare filtered with offset vs no filter + no offset then you can just load the signal a second time and compare to that
