### ISSUE TITLE
Add a headroom calculator

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#19]
Allow user to select a (wav) signal & calculate peak value
Add a filter & recalculate peak value
Show increase in dB terms
Warn if clipping

**Comment by aron7awol** [comment]
That all seems to be intuitive and make sense.

So even the result of a filter on a waveform can be calculated that quickly?  Because your remark about the speed was in the peak spectrum enhancement thread, I wasn't sure if applying the filters to the peak spectrum was really fast, or applying the filters to the waveform also.

Is your last comment just referring to the fact that someone could mix to mono and then load it into this new proposed interface, or were you referring to actually have the app perform bass-management with the signals they are filtering?  I'm guessing the first, as I would expect to second to take a long time.

**Comment by 3ll3d00d** [comment]
> So even the result of a filter on a waveform can be calculated that quickly? 

I was referring to the time it takes to apply it to the waveform. I tried this as it is a lot simpler to implement this as filter the waveform then recalculate the spectrum from the filtered waveform so that being quite quick saves me coding effort.

>  were you referring to actually have the app perform bass-management with the signals they are filtering?
yes, this will be slower (and use more RAM) but I don't expect it to be that slow so will most likely need to update the screen asynchronously, we'll see

**Comment by aron7awol** [comment]
Are you now storing the wav file location when adding the signal in order to generate the waveform?

**Comment by 3ll3d00d** [comment]
Not yet, this only works for signals added from an audio file atm
