### ISSUE TITLE
Remux auto signal mapping isn't applying to all channels

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#206]
![image](https://user-images.githubusercontent.com/42757020/51140031-74879a80-1813-11e9-9a07-c125036cc367.png)

**Comment by aron7awol** [comment]
This is what happened with a 5.1 mix I was working on.  I tested a 7.1 mix and it works properly.  Maybe that is part of steps to reproduce.

**Comment by 3ll3d00d** [comment]
this is probably the expected behaviour as it is based on the channel layouts as per https://trac.ffmpeg.org/wiki/AudioChannelManipulation#Layouts 

It should agree if the same input file is used to create the signals though as it is based on the same data

Note there are 2 5.1 layouts so I would guess the layouts are confused somewhere

    '5.1': ['FL', 'FR', 'FC', 'LFE', 'BL', 'BR'],
    '5.1(side)': ['FL', 'FR', 'FC', 'LFE', 'SL', 'SR'],

what does it say it is?

**Comment by aron7awol** [comment]
It is a decimated 5.1(side) wav extracted by BEQD from a DTS-HD MA 5.1 track.  I added all of the signals by click Add Signal then selecting the extracted wav, and leaving "Load All Channels" checked.  I entered OHF as the signal name, and the app named them all OHF_channel as it normally does.

**Comment by aron7awol** [comment]
I just checked and despite it being 5.1(side) those last two channels are named BL and BR, which does explain why it didn't work but maybe there is a valid 5.1(side) layout with BL and BR instead of SL and SR?  I didn't name them that myself.

**Comment by aron7awol** [comment]
This what MediaInfo shows on the original DTS-HD MA 5.1 track:
![image](https://user-images.githubusercontent.com/42757020/51151435-de666b00-1838-11e9-8e8d-6878e3a57f5b.png)

**Comment by 3ll3d00d** [comment]
I think the problem here is that the original track is `5.1(side)` but the decimated wav has no concept of a channel layout, it's just a 6 channel track. I have set the default channel layout for 6 channel tracks as `5.1` hence the mismatch.

I can change the default to `5.1(side)` if that is the more common layout for a 5.1 track though obviously this might be wrong at other times (if the source track was actually `5.1`). 

You could prove this is the case by doing the following

* extract audio
* select the `5.1(side)` track
* click `Add Signals` in the extract audio window
* you should now get `5.1(side)` channel naming
* add filters
* remux audio
* filters are mapped correctly

if that works as expected then there is no issue here except a 5.1 wav not having metadata hence you have to fix this yourself by renaming the channels manually or just correcting the channel mapping via the dialog.

**Comment by 3ll3d00d** [comment]
closing this one as I think the above explains it, can reopen if there is some other problem though

**Comment by aron7awol** [comment]
This issue doesn't make much difference to me personally, but I'm only thinking of a more mainstream user who uses it to do BEQ Remux.  They follow the normal workflow of the app from original file, extraction, filter creation, check headroom, remux and the app doesn't map the last 2 signals which it created itself at an earlier step.  It would be really easy for the user to miss, and they are left unaware of the fact that their file did not apply any filters to the surround channels.

I may have forgotten to specifically mention in my previous posts on this issue that I followed the full workflow with the app handling the extraction and naming of the signals upon add.

**Comment by 3ll3d00d** [comment]
I've just done that same workflow and everything worked as expected
