### ISSUE TITLE
avs post generator does not provide guidance to the user

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#284]
for @bmiller and @aron7awol

a few comments on the form

* form needs some validation, e.g. 
    - I can create post content without entering any fields
    - exception is thrown if no checkboxes are selected
    - URL fields accept invalid URLs
    - can select any combination of checkboxes (might just be unusual rather than a bug)
    - allows empty filter set to be exported (probably not desirable)
    - shortcut chosen is CTRL+P but preferences already has that so now both shortcuts are broken
    - note doesn't seem to be used
* post content could be updated in realtime
* I think there should be a select box at the top to choose TV or Film and then show the fields that are required for each 
* what is the distinction drawn between a note and a warning? 
* not obvious why we'd put exporting to XML into this form, feels a bit out of place
* would be nice to part of the title a link to some reference website (imdb or whatever) for the selected film

**Comment by bmiller** [comment]
- re: exporting xml - maybe naming this feature something else would be good for clarification. All of the data entered into the fields is also being added to the exported xml file as additional metadata.  This was actually the main purpose of starting this feature so that I could get the metadata built up for use in the browser app.  The AVS post formatting was more of a convenience so that the info could be typed in once and used for both needs.  
- Some validation could be used.  It was the initial get the base working to get feedback from Aron since it's targeted mainly for his use.  
- Any combo of checkboxes is on purpose due to streaming, UHD, and BD all potentially being different formats but the same BEQ able to be used.  
- Gah, on the shortcut. It's a platform thing.  It works on my mac since it puts the preference shortcut as cmd-, which is the mac standard.  So it looked good on my end.  I'll change it to something else.
- I'm not sure on the TV or Film selection.  It feels like extra clicks and not gaining anything over tabbing through the fields.  I was trying to keep the interaction more KISS for Aron to be able to quickly go through it.
- Note vs Warning was two different uses.  Note was intended for supplementary info that might need to be listed like when it gets checked again the BD.  The warning is for a dangerous situation like what we ran into with Furious 6 last week and gets displayed in red to warn the user.
- Added a field for the IMDB ID isn't a bad idea for linking.

**Comment by 3ll3d00d** [comment]
Build of current branch is at https://github.com/3ll3d00d/beqdesigner/releases/tag/0.9.0-alpha.1

Re TV vs film selector, most content is film so for the common case, hiding irrelevant fields is a benefit

**Comment by aron7awol** [comment]
I'll try the build.  Thanks fellas!

I agree on the TV/film selection, mostly bc the vast majority are films and the extra click to switch over to TV is worth it for the saving of extra tabs in every movie case.

In any case, this looks great and I'm excited to give it a spin!

**Comment by bmiller** [comment]
I'll look into adding a movie/tv selector that hides the season field when movie is selected.  I need to learn how to hide fields and redo space the layout now in QT. :) 

Any suggestions on what key shortcut to use since "P" doesn't work on Windows?

For "allows empty filter set to be exported (probably not desirable)" I can put a validation on opening window that filters need to be added.  We do have the possibility though that a movie comes out that's perfect and doesn't need a BEQ.  Not checking would allow it to be added to the repo to show that it has been looked at and show the user that one isn't needed.  Hey, I can dream right? ;)

**Comment by 3ll3d00d** [comment]
you can look at the minidsp dialog for an example (of hiding fields), it is basically just calling `setVisible` on the relevant fields and the layout should sort itself out automatically when you do this.

ctrl+alt+p perhaps if you want a P based shortcut

**Comment by 3ll3d00d** [comment]
have kicked off a 0.9.0-alpha.2 build which includes the (possible) fix for the crash issue, should arrive (assuming build works) in the next 10-15mins

**Comment by bmiller** [comment]
Thanks for the layout info.  I was hoping the layout girds would automatically adjust with the change but it's a first time for me in Qt so I didn't know for sure how they act.

**Comment by bmiller** [comment]
When you get a chance can we do a new build with the PR that I did last week or are there still issues with getting a new build to run for Aron?

**Comment by aron7awol** [comment]
I think the Qt error is what's preventing this build (and the median line builds) from working for me

**Comment by 3ll3d00d** [comment]
built a while ago in https://github.com/3ll3d00d/beqdesigner/releases/tag/0.9.0-alpha.2

**Comment by 3ll3d00d** [comment]
0.9.0-alpha.3 should be along shortly and is pinned to an older Qt version, give it a try and see if that helps.

**Comment by bmiller** [comment]
does alpha 3 include the changes from my PR?  I'm showing it open still.

**Comment by 3ll3d00d** [comment]
no, I commented on the PR

**Comment by bmiller** [comment]
@3ll3d00d It looks like the latest 0.7.3 betas are working for Aron.  What do I need to pull in to get the 0.9 line working for him so that he can play with the post builder?

**Comment by 3ll3d00d** [comment]
I'll rebase it

**Comment by 3ll3d00d** [comment]
I was getting multiple error dialogs at one point so I changed it to get rid of dialogs entirely and a few other tweaks (there was a missing space in the post, show live validation)

merged via https://github.com/3ll3d00d/beqdesigner/pull/302

**Comment by 3ll3d00d** [comment]
0.9.0-beta.1 should turn up shortly
