### ISSUE TITLE
0.7.3-beta.12 won't launch

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#298]
beqdesigner.exe:
```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_certifi.py", line 11, in <module>
  File "c:\tools\miniconda3\envs\test\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "ssl.py", line 98, in <module>
ImportError: DLL load failed: The specified module could not be found.
[10820] Failed to execute script pyi_rth_certifi
```
beqdesigner_small does launch but as you know still suffers from the edit bug.

**Comment by 3ll3d00d** [comment]
This seems to be machine specific behaviour as it took me 3 goes til I found a windows machine I own on which this problem occurs, still no idea what is missing as one machine it works on is my win 8.1 htpc which has no dev setup or anything

**Comment by 3ll3d00d** [comment]
might be same as https://github.com/ContinuumIO/anaconda-issues/issues/10823

**Comment by 3ll3d00d** [comment]
or might be related to https://github.com/pyinstaller/pyinstaller/issues/4048 or possibly https://github.com/pyinstaller/pyinstaller/pull/3952/files

**Comment by 3ll3d00d** [comment]
this is due to a missing ssl dll which happens to exist on some machines

a workaround is to install `openssl.light` on windows & the easiest way to do this is using chocolatey which you can install as per https://chocolatey.org/install and then do `choco install openssl.light`

alternatively wait til I work out exactly which DLLs are required and bundle them in a build

**Comment by 3ll3d00d** [comment]
I believe https://github.com/3ll3d00d/beqdesigner/releases/tag/0.7.3-beta.14 should work with the big exe, give it a try and pls let me know if it does
