### ISSUE TITLE
Builds failing for assorted reasons

### ISSUE THREAD

**Issue by 3ll3d00d** [3ll3d00d/beqdesigner#327]
python 3.8 has become the default in some cases, need to wait for https://github.com/pyinstaller/pyinstaller/issues/4311

pyinstaller failing with 

`assert self.hook_module_name not in HOOKS_MODULE_NAMES`

appears to be https://github.com/pyinstaller/pyinstaller/issues/4626

**Comment by Legorooj** [comment]
The assertion error is nothing to do with python 3.8 - it's a seperate bug that I'm currently working on a fix for. You'll need to wait until pyinstaller/pyinstaller#4311 is closed and pyinstaller officially has python 3.8 support, *and*  pyinstaller/pyinstaller#4626 is closed *with a fix*. The bug is caused when you include certain custom hook files.
