### ISSUE TITLE
0.9.6-beta.6 and above crashes on start

### ISSUE THREAD

**Issue by olegkurchin** [3ll3d00d/beqdesigner#394]
Fresh install, OSX 10.14.6
Both 0.9.6-beta.6 and 0.9.6-beta.7 crash on start without showing the main window or any error-popup. App icon is jumping a bit and then simply disappear. 
0.9.6-beta.5 is the last one working flawlessly.

**Comment by 3ll3d00d** [comment]
@olegkurchin due to changes in travis-ci policy on supporting OSS projects, I had to switch builds from travis to github. It does limit my options for creating a macos build though so now the minimum macos version provided is 10.15. Both 0.9.6 and 0.9.7-beta.1 are built using on that platform. 0.9.6 is the python 3.7 based build while 0.9.7-beta.1 is python 3.8 based.  Can you give these a try and see if they work pls

**Comment by olegkurchin** [comment]
Thanks, man! 0.9.7-beta.1 works like a charm, on OSX 10.14 as well. Appreciate
