### ISSUE TITLE
Allow multiselect on add signals

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#46]
Could the browse dialog when adding signals accept multiple selections?  I extracted 10 episodes a show but then to graph them I have to add each one at a time.

**Comment by 3ll3d00d** [comment]
FWIW this doesn't really fit into the way the add signal dialog works atm so would need a reasonable chunk of rework and/or new code to make it happen, i.e. it is one of those things that is likely to take a relatively large amount of effort to implement (relative to the benefit) so I don't expect to get round to doing this.

**Comment by aron7awol** [comment]
I thought that might be the case, but thought you had added the ability for the extraction to extract individual channels, then add all of them at once as signals, so thought maybe it wasn't that hard after all.

**Comment by 3ll3d00d** [comment]
the (relatively) time consuming bit is the UI work required to deal with multiple files in a way that makes it clear what is going on, the "add all channels" feature is already a bit of a kludge but was v little effort (as it's already handling the same file, now it just reads every channel instead of just one)

**Comment by 3ll3d00d** [comment]
no plan to implement this so closing
