### ISSUE TITLE
Eliminate padding/offset on image

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#69]
I'm trying to make a pixel-perfect report that won't resize the image at all.  I can resize the window and use Major Split Ratio and get it close, but it's not exact and it's resizing the image a tiny bit and losing quality.  I then tried to do the math based on the image size (1000x562) and size of the chart I want (2000x1000) and adjust the height (say, 1562 if not for padding) and ratio (say 0.56 if not for padding?), but I think the padding throws off my math.

Additionally, the way that the image is offset from the left edge by some pixels makes the report look asymmetrical.

**Comment by 3ll3d00d** [comment]
I'm afraid this isn't straightforward and may not even be possible at all given the way the charts are laid out

**Comment by 3ll3d00d** [comment]
> Additionally, the way that the image is offset from the left edge by some pixels makes the report look asymmetrical.

I find the alignment of the image with the chart itself rather than the tick labels looks neater myself 

just to make clear what is going on

![image](https://user-images.githubusercontent.com/2487509/46258395-d3720f80-c4c1-11e8-9386-1c54a7988697.png)

this shows that the image is plotted using a charting library and that it is sized to the "data" area, i.e. tick labels are outside the "image". If I remove the padding in this situation and attempt to extend the chart to the full width then it will clash with the tick labels.

**Comment by 3ll3d00d** [comment]
unfortunately I can't find a way to make the image expand to the full width without making it do something unexpected to the chart below, it feels like this is either a limitation of matplotlib or it requires some special incantation but I have no idea what that is. 

I think the actual solution here is to not use matplotlib for this which is I think what you were suggesting earlier, i.e. create an image of the chart, scale it to the same size as the image and then combine the two into 1 final image.

**Comment by aron7awol** [comment]
Gotcha.

I totally agree with your solution.

**Comment by 3ll3d00d** [comment]
I've implemented something that I think will pass the image through unscaled. You do need to know what you're doing to keep it happy though, here's how it works

- choose an image (if you enter a URL then the URL has to end in .jpg or .png or something like that otherwise it will cause problems later) 
- change the layout to "Pixel Perfect Image | Chart"
- the window should now resize so the chart has the same aspect ratio as the image, if this fits on your screen then it will aim for the image size but if this is bigger than your screen then it will use some size that fits on your screen but has the right aspect ratio
- tweak the chart as usual and save

The key point being that you must not change the window size after it has resized it for you if you want the image to come out in the intended format. I don't think it will blow up or anything but I haven't tested that.

Note that it currently enforces that the output is in the same format as the input so if the input is jpg then the output will be too. However since jpg is lossy and it's a whole new image then it's no longer passing the image through untouched. I have chosen a high quality jpg mode on output so I expect it should look ok however it is a variation from the original intent (albeit an unavoidable one as far as I can see).

If the original image is png on the other hand then the output is png and I would think (but can't say I'm 100% sure) this means a pristine image is passed through. Of course in this case, the resulting file will be on the large side but that also seems unavoidable.

**Comment by 3ll3d00d** [comment]
NB: I also included that extra total column in here and there are a few more controls available for tweaking the layout in other scenarios (specifically the padding around the subcharts)

**Comment by 3ll3d00d** [comment]
Closing this one for now as it is implemented but do comment back here if there are issues with this implementation.

**Comment by aron7awol** [comment]
I think higher quality resize would be a nice addition, just to make the app a one-stop-shop without having to use another tool.

**Comment by aron7awol** [comment]
I tested it and it does work, but the chart ends up too small with only 1000px width.  I was considering keeping the image at 1000px wide and have the chart at something wider, but that's a whole other story and probably not worth pursuing.

I like the ability to get rid of the padding between the image and chart by setting height spacing to 0, so thanks for that addition.  I'd still love to get rid of all padding around the image, but I know that would be a separate item.  I'll just keep rolling with what I've been doing with the new abilities you just added.  Thanks!

**Comment by aron7awol** [comment]
Actually, I see you added actual size of image so now I can try the different widths.

**Comment by 3ll3d00d** [comment]
atm there is no explicit control in the app over the size of the image, it's either "force the chart to be the same width as the image" (the "pixel perfect chart" layout) or you can influence the chart size based on layout, padding and split ratio which will result in a chart that is no wider (i.e. might be narrower) than the chart.

Another alternative would be to rescale the image to the actual chart size but I'm not sure if that is really worth the effort (as it really is v little effort to rescale the image outside the app). 

If there is some other approach desired then raise the issue and I'll add it if is something I can add v quickly.

**Comment by aron7awol** [comment]
Gotcha.

I do agree that rescaling the image (high quality rescale ideally) to the chart size and then combining the two into a single image is a great approach.  That's the ideal approach in my mind.

I agree it's not hard to rescale the image outside the app, and combine the two images outside the app, but the current setup is pretty much fully automated (generate report, paste image URL, save report) so I'd prefer to continue with the current workflow rather than introduce those repetitive steps outside the app.

Again, I appreciate your work, and understand completely if you're not willing to do some enhancements.
