### ISSUE TITLE
Analyse Audio clumps data towards the start of the signal

### ISSUE THREAD

**Issue by aron7awol** [3ll3d00d/beqdesigner#87]
I am trying to figure out how the different functions within Analyse Audio work...

Under peak spectrum, I can see the y-axis is the time in seconds, x-axis is frequency, and the color of the dot is determined by dB, but what is throwing me off, is every time I load a file, the dots are bunched up near the bottom (or beginning of the file in terms of time), and I know not all of these films are loudest at the beginning :)  I am also curious exactly what clip to absolute peak, clip to average, clip to specific dB will do.

Sorry if this wasn't the proper place to ask this.  It was either this, post in the BEQ thread, or PM you on AVS!

**Comment by 3ll3d00d** [comment]
Consider this an experimental feature :)

The idea is to be able to look at an entire track and quickly find the parts that have stronger content. The not implemented bit is to be able to zoom into some interesting short section and show an actual spectrograph.

To do this, in a way that is quick to calculate and quick to render, i thought of creating a scatter plot from the peak spectrum data. If you think of how the analysis works, it chops the track up into a series of short, overlapping segments and then computes the average and peak spectrum for each segment. The resulting peak is the peak of the peaks and the average is the average of the averages if you get what I mean.

This plot is taking the peak spectrum per period data and filtering (aka clipping because I am discarding data points that don't meet the filter) it according to how far from the peak it is. 

Clip to absolute peak means relative to the absolute peak in the whole track (independent of Freq), clip to average means show all peak data that has a magnitude greater than the average, clip to dB means peak data greater than -x dB below the whole track peak for that frequency

Make sense?

**Comment by 3ll3d00d** [comment]
I haven't tested it extensively but don't recall bunching at the start of the track, some examples might help here

**Comment by aron7awol** [comment]
Thank you.  Your explanation makes perfect sense, and is exactly how I thought it worked, but what was making me question it was the bunching I referred to.  My home internet is down at the moment but once it's back up I will post some screenshots to show you the bunching issue.  I've tested probably close to a dozen tracks and all seemed to suffer from this issue, so maybe there's a bug in there.

**Comment by aron7awol** [comment]
Here are a few examples:
![image](https://user-images.githubusercontent.com/42757020/46507262-ab5a1780-c805-11e8-9f65-1a44ccba5ecd.png)
![image](https://user-images.githubusercontent.com/42757020/46507284-c62c8c00-c805-11e8-99a2-2bf4968e6eb7.png)
![image](https://user-images.githubusercontent.com/42757020/46507301-d93f5c00-c805-11e8-93e1-bdfe0943f108.png)
![image](https://user-images.githubusercontent.com/42757020/46507314-ee1bef80-c805-11e8-8d1f-a0c7f7096c27.png)
![image](https://user-images.githubusercontent.com/42757020/46507335-0429b000-c806-11e8-9762-99d6b976c862.png)

**Comment by 3ll3d00d** [comment]
does look dodgy, will dig into it

**Comment by aron7awol** [comment]
Awesome, I'm excited to play with this!

Do you mind doing a release with just this fix?

**Comment by 3ll3d00d** [comment]
was just cutting one and will post on avs to explain how to use :)
